### ISSUE TITLE
大神有试过用dumpdecrypted砸壳后生成ipa文件再用到MonkeyDev里去吗？

### ISSUE THREAD

**Issue by wonderffee** [AloneMonkey/dumpdecrypted#1]
现在的问题是我能用dumpdecrpted砸壳，但是只砸了armv7的，thin之后不知道怎么正确生成越狱ipa安装包，我现在的方式是把thin之后的decrypt binary文件替换旧的binary文件，然后压缩生成zip文件改后缀为ipa文件，用iFunBox安装不成功，感觉不是真正的越狱ipa，求教一下还需要什么步骤生成真正的越狱ipa文件

**Comment by wonderffee** [comment]
clutch砸壳的ipa倒是能安装但是运行闪退

**Comment by AloneMonkey** [comment]
解密后的动态库也需要替换，全部替换后压缩成ipa就行。
如果只有armv7的架构放到MonkeyDev里面需要将所有动态库的Build Settings下Build Active Architecture Only Debug改成No

**Comment by wonderffee** [comment]
说的动态库是ipa里面带的framework吗？是要解密framework再替换？不知道这个在原始的ipa里面是否是加密的，之前试过要重签名的话这个framework好像也要重签名

**Comment by AloneMonkey** [comment]
是的，自动的framework需要解密的，使用otool -l xxx | grep crypt 查看加密状态，MonkeyDev会自动重签所有三方库。

**Comment by wonderffee** [comment]
我回去试试，谢谢回答
