### ISSUE TITLE
编译时报链接拒绝的错误，应该如何获取非越狱手机的ip地址和端口号？

### ISSUE THREAD

**Issue by fsp1990** [AloneMonkey/dumpdecrypted#2]
我的手机（非越狱）通过usb链接到mac， 如何操作才能ssh到手机上呢，视频教程里面看到的你是做的usb端口映射？how？

ssh: connect to host localhost port 2222: Connection refused
Failed to create directory /var/root/MonkeyDevPackages on device localhost
Command /bin/sh failed with exit code 255

**Comment by AloneMonkey** [comment]
非越狱是不能砸壳的。

**Comment by dylib** [comment]
这是否意味着它不能用于非越狱？

**Comment by AloneMonkey** [comment]
nop
