### ISSUE TITLE
动态调试 iproxy 1234 1234

### ISSUE THREAD

**Issue by xhzth7091** [AloneMonkey/dumpdecrypted#6]
动态调试 ，你推荐做端口转发,iproxy 1234 1234,报错 zsh: command not found: iproxy
![Xnip2019-05-07_11-03-52](https://user-images.githubusercontent.com/13980546/57268800-d10b1000-70b7-11e9-9682-f5ed4846f36d.jpg)

**Comment by jakciehoo** [comment]
安装 usbmuxd
